# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: devcontainer-lock.json
      - id: trailing-whitespace
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs
      - id: check-added-large-files
        args: [--maxkb=50, --enforce-all] # increase or add git lfs if too strict
        exclude: ^MODULE\.bazel\.lock$
  - repo: local
    hooks:
      - id: yamlfmt
        name: yamlfmt
        entry: tools/run_tool.sh yamlfmt
        language: system
        types: [yaml]
      - id: shellcheck
        name: shellcheck
        entry: tools/run_tool.sh shellcheck
        language: system
        types: [shell]
      - id: reuse
        name: reuse
        entry: tools/run_tool.sh reuse lint
        language: system
        always_run: true
        pass_filenames: false
  - repo: https://github.com/eclipse-score/tooling
    rev: 31ff8eee214e4e97ef8f5cb46e443273515b63ec
    hooks:
      - id: copyright
